fusions = [
new Fusion("fire", "water", ['steam']),
new Fusion("dust", "dust", ['dustStorm']),
new Fusion("water", "water", ['sea']),
new Fusion("water", "air", ['mist']),
new Fusion("water", "earth", ['mud']),
new Fusion("mud", "air", ['earth']),
new Fusion("dust", "water", ['mud']),
new Fusion("earth", "earth", ['pressure']),
new Fusion("mud", "pressure", ['clay']),
new Fusion("clay", "dust", ['urn']),
new Fusion("earth", "sea", ['sand']),
new Fusion("earth", "air", ['dust']),
new Fusion("clay", "fire", ['brick']),
new Fusion("brick", "brick", ['house']),
new Fusion("house", "house", ['city']),
new Fusion("city", "city", ['country']),
new Fusion("country", "country", ['planet']),
new Fusion("mist", "mist", ['cloud']),
new Fusion("cloud", "cloud", ['sky']),
new Fusion("sky", "water", ['rain']),
new Fusion("planet", "fire", ['climateChange']),
new Fusion("planet", "water", ['theIncident']),
new Fusion("earth", "rain", ['grass']),
new Fusion("grass", "rain", ['tree']),
new Fusion("grass", "water", ['tree']),
new Fusion("fire", "tree", ['smoke', 'charcoal']),
new Fusion("sand", "pressure", ['stone']),
new Fusion("tree", "tree", ['forest']),
new Fusion("fire", "charcoal", ['energy']),
new Fusion("fire", "stone", ['metal']),
]