materials = {
    fire: {name: "Fire", },
    water: {name: "Water"},
    earth: {name: "Earth"},
    air: {name: "Air"},
    smoke: {name: "Smoke"},
    dustStorm: {name: "Dust Storm", terminal: true},
    mist: {name: "Mist"},
    sea: {name: "Sea"},
    mud: {name: "Mud"},
    clay: {name: "Clay"},
    sand: {name: "Sand"},
    dust: {name: "Dust"},
    urn: {name: "Urn", terminal: true},
    pressure: {name: "Pressure"},
    cloud: {name: "Cloud"},
    sky: {name: "Sky"},
    rain: {name: "Rain"},
    brick: {name: "Brick"},
    house: {name: "House"},
    city: {name: "City"},
    country: {name: "Country"},
    planet: {name: "Planet"},
    steam: {name: "Steam"}   
}